"""事件类型常量：每一条事件都是一条可核验的决策记录。"""


class EventType:
    PARTY_REGISTERED = "PARTY_REGISTERED"
    DRAFT_CREATED = "DRAFT_CREATED"
    TERM_PROPOSED = "TERM_PROPOSED"
    TERM_REVISED = "TERM_REVISED"
    TERM_COUNTERSIGNED = "TERM_COUNTERSIGNED"
    VERSION_ACTIVATED = "VERSION_ACTIVATED"
    AMENDMENT_PROPOSED = "AMENDMENT_PROPOSED"
    AMENDMENT_COUNTERSIGNED = "AMENDMENT_COUNTERSIGNED"
    AMENDMENT_ENACTED = "AMENDMENT_ENACTED"
    OBLIGATION_REGISTERED = "OBLIGATION_REGISTERED"
    OBLIGATION_SUPERSEDED = "OBLIGATION_SUPERSEDED"
    FULFILLMENT_RECORDED = "FULFILLMENT_RECORDED"
    DISPUTE_RAISED = "DISPUTE_RAISED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    SUBSTITUTE_RECORDED = "SUBSTITUTE_RECORDED"
